name:                server-haskell
version:             0.1.0.0
license:             BSD3
author:              "ircmq-boys"
maintainer:          "sebbern@stud.ntnu.no"
copyright:           "2021 Dennis Kristiansen, Sebastian Lindtvedt, Salvador Bascunan"

extra-source-files:
- README.md

description:         Chat server based on zeromq.

dependencies:
- base >= 3 && < 5
- containers
- bytestring >= 0.11.1.0
- zeromq4-haskell
- aeson >= 1.5 && < 1.6
- mtl

library:
  source-dirs: src

executables:
  server-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server-haskell

tests:
  server-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server-haskell
